---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kor.serviceAccountName" . }}-read-resources-role-binding
  labels:
    {{- include "kor.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kor.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "kor.serviceAccountName" . }}-read-resources-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kor.serviceAccountName" . }}-read-resources-clusterrolebinding
  labels:
    {{- include "kor.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kor.serviceAccountName" . }}
    namespace: {{ include "kor.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "kor.serviceAccountName" . }}-read-resources-clusterrole
  apiGroup: rbac.authorization.k8s.io
